/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as HeightsRouteImport } from './routes/heights'
import { Route as GreenValleyRouteImport } from './routes/green-valley'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BusinessParkRouteImport } from './routes/business-park'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const HeightsRoute = HeightsRouteImport.update({
  id: '/heights',
  path: '/heights',
  getParentRoute: () => rootRouteImport,
} as any)
const GreenValleyRoute = GreenValleyRouteImport.update({
  id: '/green-valley',
  path: '/green-valley',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessParkRoute = BusinessParkRouteImport.update({
  id: '/business-park',
  path: '/business-park',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-park': typeof BusinessParkRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/green-valley': typeof GreenValleyRoute
  '/heights': typeof HeightsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-park': typeof BusinessParkRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/green-valley': typeof GreenValleyRoute
  '/heights': typeof HeightsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-park': typeof BusinessParkRoute
  '/buy': typeof BuyRoute
  '/contact': typeof ContactRoute
  '/green-valley': typeof GreenValleyRoute
  '/heights': typeof HeightsRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business-park'
    | '/buy'
    | '/contact'
    | '/green-valley'
    | '/heights'
    | '/portfolio'
    | '/privacy'
    | '/projects'
    | '/sell'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business-park'
    | '/buy'
    | '/contact'
    | '/green-valley'
    | '/heights'
    | '/portfolio'
    | '/privacy'
    | '/projects'
    | '/sell'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business-park'
    | '/buy'
    | '/contact'
    | '/green-valley'
    | '/heights'
    | '/portfolio'
    | '/privacy'
    | '/projects'
    | '/sell'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessParkRoute: typeof BusinessParkRoute
  BuyRoute: typeof BuyRoute
  ContactRoute: typeof ContactRoute
  GreenValleyRoute: typeof GreenValleyRoute
  HeightsRoute: typeof HeightsRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  SellRoute: typeof SellRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heights': {
      id: '/heights'
      path: '/heights'
      fullPath: '/heights'
      preLoaderRoute: typeof HeightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/green-valley': {
      id: '/green-valley'
      path: '/green-valley'
      fullPath: '/green-valley'
      preLoaderRoute: typeof GreenValleyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-park': {
      id: '/business-park'
      path: '/business-park'
      fullPath: '/business-park'
      preLoaderRoute: typeof BusinessParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessParkRoute: BusinessParkRoute,
  BuyRoute: BuyRoute,
  ContactRoute: ContactRoute,
  GreenValleyRoute: GreenValleyRoute,
  HeightsRoute: HeightsRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  SellRoute: SellRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
